export const MODULES = {
  ACTIONS: 'ACTIONS',
  APPLICATIONS: 'APPLICATIONS',
  MODULES: 'MODULES',
  MENU_OPTIONS: 'MENU_OPTIONS',
  ROLES: 'ROLES',
  PERMISSIONS: 'PERMISSIONS',
  USERS: 'USERS',
  SETTINGS: 'SETTINGS',
  LOTES: 'LOTES',
}
